# Generated by Django 3.1.7 on 2021-04-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrauntdetail',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
